<?php

/**
 * @var \Aht\Custom\Block\Adminhtml\Department\Manage $block
 */

$departments = $block->getDepartments();
$adminUrl = $block->getBaseUrl() . $this->helper('Magento\Backend\Helper\Data')->getAreaFrontName();
?>
<button class="add-department"><a href="<?= $block->getAddUrl(); ?>">Add New</a></button>
<table>
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Action</th>
	</tr>
<?php foreach ($departments as $department): ?>
	<tr>
		<td><?= $department->getId(); ?></td>
		<td><?= $department->getName(); ?></td>
		<td>
			<a href="<?= $block->getDetailUrl($department->getId()); ?>">Edit</a>
			<a href="<?= $block->getDeleteUrl($department->getId()); ?>">Delete</a>
		</td>
	</tr>
<?php endforeach; ?>
</table>

<style>
	.add-department{
		margin-bottom: 10px;
	}
	table{
		text-align: center;
	}
	table tr th,
	table tr td{
		border: 1px solid black;
		padding: 10px;
	}
</style>