<?php 
	$departments = $block->getDepartments();
	$employees = $block->getEmployees();
?>


<h2>Department:</h2>
<table>
	<tr>
		<th>ID</th>
		<th>Name</th>
	</tr>
<?php foreach ($departments as $department): ?>
	<tr>
		<td><?= $department->getId(); ?></td>
		<td><?= $department->getName(); ?></td>
	</tr>
<?php endforeach; ?>
</table>

<h2>Employee:</h2>
<table>
	<tr>
		<th>ID</th>
		<th>Department Name</th>
		<th>Email</th>
		<th>Employee Name</th>
		<th>Service Year</th>
		<th>Dob</th>
		<th>Salary</th>
		<th>VAT</th>
		<th>Note</th>
	</tr>
<?php foreach ($employees as $employee): ?>
	<tr>
		<td><?= $employee->getId(); ?></td>
		<td><?= $employee->getDepartmentName(); ?></td>
		<td><?= $employee->getEmail(); ?></td>
		<td><?= $employee->getFirstName() . ' ' . $employee->getLastName(); ?></td>
		<td><?= $employee->getServiceYears(); ?></td>
		<td><?= $employee->getDob(); ?></td>
		<td><?= $employee->getSalary(); ?></td>
		<td><?= $employee->getVatNumber(); ?></td>
		<td><?= $employee->getNote(); ?></td>
	</tr>
<?php endforeach; ?>
</table>

<style>
	table{
		text-align: center;
		margin-bottom: 20px;
	}
	table tr th,
	table tr td{
		border: 1px solid black;
		padding: 10px;
		text-align: center;
	}
</style>